apiVersion: apps/v1
kind: Deployment
metadata:
  name: fcg-ms-payments
  labels:
    app: fcg-ms-payments
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fcg-ms-payments
  template:
    metadata:
      labels:
        app: fcg-ms-payments
    spec:
      containers:
        - name: fcg-ms-payments
          image: 773016904081.dkr.ecr.us-east-1.amazonaws.com/payments:latest
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
            - name: Stripe__PublishableKey
              valueFrom:
                secretKeyRef:
                  name: fcg-ms-payments-secret
                  key: Stripe__PublishableKey
            - name: Stripe__SecretKey
              valueFrom:
                secretKeyRef:
                  name: fcg-ms-payments-secret
                  key: Stripe__SecretKey
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: fcg-ms-payments-service
  labels:
    app: fcg-ms-payments
spec:
  type: LoadBalancer
  selector:
    app: fcg-ms-payments
  ports:
    - port: 80
      targetPort: 80
